title: Minecraft Server Menu
description: >-
  Do you want an easy, fast and organized method to create a Minecraft Server? 
  come and meet Minecraft Server Menu a .Batch file, very fast managing Backups, Server, Client, Moderation, Mods and Plugins! 
  <3 thx for support!

# url system:
default_port: "4000" # define here the Port from your "jekyll server"
baseurl: "MinecraftServerMenu" # MinecraftServerMenu if you gona run he in localhost remember to define null or use "$ jekyll server --baseurl=''"
url: ""

# others:

github_username: gabrielramires
youtube_username: GabrielRamires

# Theme:
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
