title: Minecraft Server Menu
description: >-
  Do you want an easy, fast and organized method to create a Minecraft Server? 
  come and meet Minecraft Server Menu a .Batch file, very fast managing Backups, Server, Client, Moderation, Mods and Plugins! 
  <3 thx for support!

# url system:
<<<<<<< HEAD
baseurl: "" # MinecraftServerMenu
=======
default_port: "4000" # define here the Port from your "jekyll server"
baseurl: "MinecraftServerMenu" # MinecraftServerMenu if you gona run he in localhost remember to define null or use "$ jekyll server --baseurl=''"
>>>>>>> 3bd1c058657589c65ab07200f0871d2a282c43eb
url: ""
port: 2000

# others:
<<<<<<< HEAD
github_username: RamiresOliv
=======

github_username: gabrielramires
youtube_username: GabrielRamires
>>>>>>> 3bd1c058657589c65ab07200f0871d2a282c43eb

# Theme:
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

default_port: "2000" # define here the Port from your "jekyll server"
