version: "2.1"
orbs:
  gh-pages: sugarshin/gh-pages@x.y.z
jobs:
  build_deploy:
    executor: gh-pages/default
    steps:
      - checkout
      - run: ./build.sh
      - gh-pages/deploy:
          setup-git: true
          ssh-fingerprints: <fingerprint>
workflows:
  Build and Deploy:
    jobs:
      - build_deploy
