# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  gh-pages: sugarshin/gh-pages@1.0.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build_deploy:
    executor: gh-pages/default
    steps:
      - checkout
      - run: dir && ./build.sh
      - gh-pages/deploy:
          setup-git: true
          ssh-fingerprints: <fingerprint>

workflows:
  Build and Deploy:
    jobs:
      - build_deploy
